name: golangci-lint-k6
description: Run golangci-lint with the k6 ruleset

runs:
  using: composite
  steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.x
        check-latest: true
    - name: Get golangci-lint version and download rules
      shell: bash
      run: |
        RulesURL="https://raw.githubusercontent.com/grafana/k6/${{ github.action_ref }}/.golangci.yml"
        echo "Downloading ${RulesURL}..."
        curl "${RulesURL}" --output "${{ github.action_path }}/.golangci.yml"

        echo "GolangCIVersion=$(head -n 1 "${{ github.action_path }}/.golangci.yml" | tr -d '# ')" >> $GITHUB_OUTPUT
      id: getenv
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: ${{ steps.getenv.outputs.GolangCIVersion }}
        only-new-issues: true
        args: "--config=${{ github.action_path }}/.golangci.yml"
